// <auto-generated />
using System;
using Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infra.Migrations
{
    [DbContext(typeof(MySqlContext))]
    [Migration("20230204192503_initialMigration")]
    partial class initialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Domain.Entities.Freight", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Boxes")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Dellivery")
                        .HasColumnType("int");

                    b.Property<string>("Destination")
                        .HasColumnType("longtext");

                    b.Property<string>("Driver")
                        .HasColumnType("longtext");

                    b.Property<string>("FreightTable")
                        .HasColumnType("longtext");

                    b.Property<int?>("Km")
                        .HasColumnType("int");

                    b.Property<string>("Origin")
                        .HasColumnType("longtext");

                    b.Property<string>("Plate")
                        .HasColumnType("longtext");

                    b.Property<int?>("TravelNumber")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("TravelType")
                        .HasColumnType("longtext");

                    b.Property<int?>("TravelValue")
                        .HasColumnType("int");

                    b.Property<string>("VechicleType")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Freight", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.FreightPrice", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Client")
                        .HasColumnType("longtext");

                    b.Property<string>("Destination")
                        .HasColumnType("longtext");

                    b.Property<string>("TableName")
                        .HasColumnType("longtext");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.Property<string>("VechicleType")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("FreightPrice", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
